export const WEEKLY_CHALLENGE_IDS = [
  "meet-new-parent",
  "learn-parent-child-names",
  "genuine-parent-compliment",
  "invite-parent-nearby",
  "welcome-new-parent",
  "encourage-another-child",
  "introduce-two-parents",
  "help-small-sideline-need",
  "ask-lighthearted-question",
  "start-humorous-conversation",
  "discover-shared-interest",
  "say-hello-first",
  "talk-to-someone-alone",
  "thank-team-parent",
  "offer-useful-tip",
  "compliment-sportsmanship",
  "connect-after-activity",
] as const;

export type WeeklyChallengeId = (typeof WEEKLY_CHALLENGE_IDS)[number];

type WeeklyChallengeTranslation = { title: string; description: string };

export const weeklyChallengeTranslations = {
  en: {
    "meet-new-parent": { title: "Meet Someone New", description: "Introduce yourself to one parent you have not met before." },
    "learn-parent-child-names": { title: "Learn Their Names", description: "Learn the name of another parent and their child." },
    "genuine-parent-compliment": { title: "Share a Genuine Compliment", description: "Give another parent a genuine compliment about something unrelated to their child's performance." },
    "invite-parent-nearby": { title: "Save a Seat", description: "Invite another parent to sit or stand near you instead of remaining alone." },
    "welcome-new-parent": { title: "Welcome a New Parent", description: "Introduce yourself to a parent who appears new to the team, league, or activity." },
    "encourage-another-child": { title: "Cheer Together", description: "Encourage or celebrate another parent's child during the game or practice." },
    "introduce-two-parents": { title: "Make an Introduction", description: "Introduce two parents who have not met but may have something in common." },
    "help-small-sideline-need": { title: "Lend a Hand", description: "Help another parent with a small sideline need, such as carrying a chair, sharing information, or briefly watching their belongings." },
    "ask-lighthearted-question": { title: "Ask a Fun Question", description: "Ask another parent a lighthearted question, such as their favorite snack, team tradition, or sport to watch." },
    "start-humorous-conversation": { title: "Share a Sideline Laugh", description: "Start a fun or humorous conversation with another parent about a relatable sideline moment." },
    "discover-shared-interest": { title: "Find Common Ground", description: "Discover one interest you share with another parent that is unrelated to youth sports." },
    "say-hello-first": { title: "Say Hello First", description: "Be the first person to say hello when arriving at a practice or game." },
    "talk-to-someone-alone": { title: "Include Someone", description: "Start a conversation with someone who is sitting or standing alone." },
    "thank-team-parent": { title: "Show Appreciation", description: "Thank another parent for something they contribute to the team community." },
    "offer-useful-tip": { title: "Share a Helpful Tip", description: "Offer another parent a useful, low-pressure tip, such as where to park, what to bring, or where nearby facilities are located." },
    "compliment-sportsmanship": { title: "Celebrate Good Sportsmanship", description: "Compliment another parent when you notice their child showing teamwork, kindness, or good sportsmanship." },
    "connect-after-activity": { title: "Stay and Connect", description: "Spend a few minutes after the activity talking with another parent instead of leaving immediately." },
  },
  es: {
    "meet-new-parent": { title: "Conoce a alguien nuevo", description: "Preséntate a una madre o un padre que aún no conozcas." },
    "learn-parent-child-names": { title: "Aprende sus nombres", description: "Aprende el nombre de otra madre o padre y el de su hijo o hija." },
    "genuine-parent-compliment": { title: "Comparte un cumplido sincero", description: "Hazle a otra madre o padre un cumplido sincero sobre algo que no tenga que ver con el desempeño de su hijo o hija." },
    "invite-parent-nearby": { title: "Guarda un lugar", description: "Invita a otra madre o padre a sentarse o quedarse cerca de ti en vez de permanecer a solas." },
    "welcome-new-parent": { title: "Da la bienvenida a alguien nuevo", description: "Preséntate a una madre o un padre que parezca nuevo en el equipo, la liga o la actividad." },
    "encourage-another-child": { title: "Animen juntos", description: "Anima o celebra al hijo o la hija de otra familia durante el partido o la práctica." },
    "introduce-two-parents": { title: "Haz una presentación", description: "Presenta a dos madres o padres que aún no se conozcan y que quizá tengan algo en común." },
    "help-small-sideline-need": { title: "Echa una mano", description: "Ayuda a otra familia con algo pequeño en la cancha, como llevar una silla, compartir información o cuidar sus pertenencias por un momento." },
    "ask-lighthearted-question": { title: "Haz una pregunta divertida", description: "Hazle a otra madre o padre una pregunta amena, como cuál es su bocadillo favorito, una tradición del equipo o qué deporte le gusta ver." },
    "start-humorous-conversation": { title: "Compartan una risa", description: "Inicia una conversación divertida con otra madre o padre sobre algún momento típico de la vida junto a la cancha." },
    "discover-shared-interest": { title: "Encuentra algo en común", description: "Descubre un interés que compartas con otra madre o padre y que no esté relacionado con los deportes juveniles." },
    "say-hello-first": { title: "Saluda primero", description: "Sé la primera persona en saludar al llegar a una práctica o un partido." },
    "talk-to-someone-alone": { title: "Incluye a alguien", description: "Inicia una conversación con alguien que esté sentado o de pie a solas." },
    "thank-team-parent": { title: "Muestra tu agradecimiento", description: "Agradece a otra madre o padre por algo que aporte a la comunidad del equipo." },
    "offer-useful-tip": { title: "Comparte un consejo útil", description: "Ofrece un consejo útil y sin presión, como dónde estacionarse, qué llevar o dónde están las instalaciones cercanas." },
    "compliment-sportsmanship": { title: "Celebra el buen espíritu deportivo", description: "Felicita a otra madre o padre cuando notes que su hijo o hija demuestra compañerismo, amabilidad o buen espíritu deportivo." },
    "connect-after-activity": { title: "Quédate a conversar", description: "Dedica unos minutos después de la actividad a conversar con otra madre o padre en vez de irte de inmediato." },
  },
} satisfies Record<"en" | "es", Record<WeeklyChallengeId, WeeklyChallengeTranslation>>;
