import type { CoachCommunicationTemplate } from "@/types/coachResources";

const text = (en: string, es: string) => ({ en, es });
const template = (
  id: string,
  category: CoachCommunicationTemplate["category"],
  order: number,
  title: [string, string],
  description: [string, string],
  body: [string, string],
  placeholders: string[],
): CoachCommunicationTemplate => ({
  id, category, title: text(...title), description: text(...description), body: text(...body), placeholders,
  canSendAsAnnouncement: category !== "message_parent",
  ...(category !== "message_parent" ? { defaultAnnouncementAudience: "all" as const } : {}),
  sortOrder: order, isActive: true, contentVersion: 1,
});

export const COACH_COMMUNICATION_TEMPLATES: CoachCommunicationTemplate[] = [
  template("practice-reminder", "schedule", 10, ["Practice Reminder", "Recordatorio de Práctica"],
    ["Share the essentials before practice.", "Comparte lo esencial antes de la práctica."],
    ["Hi {teamName} families! Practice is scheduled for {date} at {time} at {venue}. Please have players arrive {arrivalMinutes} minutes early with water and {equipment}. See you there!", "¡Hola, familias de {teamName}! La práctica está programada para el {date} a las {time} en {venue}. Por favor, lleguen {arrivalMinutes} minutos antes con agua y {equipment}. ¡Nos vemos!"],
    ["teamName", "date", "time", "venue", "arrivalMinutes", "equipment"]),
  template("game-day-reminder", "schedule", 20, ["Game-Day Reminder", "Recordatorio del Día de Juego"],
    ["Set expectations for arrival and equipment.", "Aclara la llegada y el equipo necesario."],
    ["Hello {teamName}! Our game is {date} at {time} at {venue}. Please arrive {arrivalMinutes} minutes early wearing the required uniform and bring {equipment}. We look forward to a positive day together.", "¡Hola, {teamName}! Nuestro juego es el {date} a las {time} en {venue}. Lleguen {arrivalMinutes} minutos antes con el uniforme requerido y {equipment}. Esperamos compartir un día positivo."],
    ["teamName", "date", "time", "venue", "arrivalMinutes", "equipment"]),
  template("practice-cancellation", "schedule", 30, ["Practice Cancellation", "Cancelación de Práctica"],
    ["Cancel clearly and share the next step.", "Cancela con claridad y comparte el siguiente paso."],
    ["Hi {teamName} families. Today's practice at {time} is canceled because {reason}. Please watch the team announcements for our next update. Thank you for understanding.", "Hola, familias de {teamName}. La práctica de hoy a las {time} queda cancelada porque {reason}. Revisen los anuncios del equipo para la próxima actualización. Gracias por su comprensión."],
    ["teamName", "time", "reason"]),
  template("weather-delay", "schedule", 40, ["Weather Delay", "Demora por Clima"],
    ["Communicate a delay without guessing.", "Comunica una demora sin hacer suposiciones."],
    ["Hi {teamName} families. We are delaying today's activity because of current weather conditions. Please wait for an update at {time} and follow league or facility safety guidance. Thank you for your patience.", "Hola, familias de {teamName}. Estamos demorando la actividad de hoy debido al clima actual. Esperen una actualización a las {time} y sigan las indicaciones de seguridad de la liga o instalación. Gracias por su paciencia."],
    ["teamName", "time"]),
  template("location-change", "schedule", 50, ["Location Change", "Cambio de Lugar"],
    ["Make a venue change easy to find.", "Haz que el cambio de lugar sea fácil de encontrar."],
    ["Hello {teamName}. Our {date} activity has moved to {newLocation}. The start time remains {time}. Please reply through the approved team channel if you need clarification.", "Hola, {teamName}. La actividad del {date} se trasladó a {newLocation}. La hora de inicio sigue siendo {time}. Respondan por el canal aprobado del equipo si necesitan aclaración."],
    ["teamName", "date", "newLocation", "time"]),
  template("equipment-reminder", "schedule", 60, ["Uniform or Equipment Reminder", "Recordatorio de Uniforme o Equipo"],
    ["Remind families what players need.", "Recuerda a las familias lo que necesitan los jugadores."],
    ["Friendly reminder for {teamName}: please bring {equipment} to {venue} on {date}. Label personal items when appropriate and let the coaching staff know privately if you need help with an approved equipment option.", "Recordatorio para {teamName}: por favor, lleven {equipment} a {venue} el {date}. Marquen los artículos personales cuando corresponda y avisen en privado al staff si necesitan ayuda con una opción aprobada."],
    ["teamName", "equipment", "venue", "date"]),
  template("welcome-team", "parents", 70, ["Welcome to the Team", "Bienvenida al Equipo"],
    ["Begin the season with warmth and clarity.", "Comienza la temporada con calidez y claridad."],
    ["Welcome to {teamName}! I'm {coachName}, and I'm excited to support a positive, active season. We will use the team announcement space for schedules and updates. Our first gathering is {date} at {time} at {venue}. I look forward to meeting everyone.", "¡Bienvenidos a {teamName}! Soy {coachName} y me entusiasma apoyar una temporada positiva y activa. Usaremos los anuncios del equipo para horarios y novedades. Nuestro primer encuentro es el {date} a las {time} en {venue}. Espero conocerlos pronto."],
    ["teamName", "coachName", "date", "time", "venue"]),
  template("volunteer-request", "parents", 80, ["Volunteer Request", "Solicitud de Voluntarios"],
    ["Ask for specific, manageable help.", "Solicita ayuda específica y manejable."],
    ["Hi {teamName} families. We could use volunteer help with {reason} on {date}. If you are available, please respond through the team channel. Every contribution helps us create a smooth experience for the players. Thank you!", "Hola, familias de {teamName}. Necesitamos voluntarios para ayudar con {reason} el {date}. Si están disponibles, respondan por el canal del equipo. Cada contribución ayuda a crear una buena experiencia para los jugadores. ¡Gracias!"],
    ["teamName", "reason", "date"]),
  template("supply-reminder", "parents", 90, ["Snack or Supply Reminder", "Recordatorio de Snacks o Suministros"],
    ["Send a practical supply reminder.", "Envía un recordatorio práctico de suministros."],
    ["Hello {teamName} families. This is a reminder about {equipment} for {date}. Please follow league guidance for allergies, food, and shared supplies. Contact the coaching staff privately with questions.", "Hola, familias de {teamName}. Este es un recordatorio sobre {equipment} para el {date}. Sigan las indicaciones de la liga sobre alergias, alimentos y suministros compartidos. Consulten en privado al staff si tienen preguntas."],
    ["teamName", "equipment", "date"]),
  template("parent-concern", "message_parent", 100, ["Addressing a Parent Concern", "Responder a una Inquietud Familiar"],
    ["Acknowledge a concern and propose a calm next step.", "Reconoce la inquietud y propone un próximo paso tranquilo."],
    ["Thank you for sharing your concern. I want every player to have a positive experience. Could we speak privately at {time} so I can listen carefully and we can agree on an appropriate next step?", "Gracias por compartir su inquietud. Quiero que cada jugador tenga una experiencia positiva. ¿Podemos hablar en privado a las {time} para que pueda escuchar con atención y acordar un próximo paso apropiado?"],
    ["time"]),
  template("private-conversation", "message_parent", 110, ["Requesting a Private Conversation", "Solicitar una Conversación Privada"],
    ["Move a sensitive topic away from the team space.", "Lleva un tema sensible fuera del espacio del equipo."],
    ["Hi. I'd like to discuss {reason} privately so we can give it the attention it deserves. Would {date} at {time} work for a brief conversation? Please do not share private player details in the team announcement space.", "Hola. Me gustaría conversar en privado sobre {reason} para prestarle la atención que merece. ¿Le serviría el {date} a las {time} para una conversación breve? Por favor, no comparta detalles privados de jugadores en los anuncios del equipo."],
    ["reason", "date", "time"]),
  template("difficult-follow-up", "message_parent", 120, ["Following Up After a Private Conversation", "Seguimiento Después de una Conversación Privada"],
    ["Re-center a conversation on a constructive next step.", "Vuelve a centrar la conversación en un próximo paso constructivo."],
    ["Thank you for speaking with me about {reason}. I appreciate the chance to listen. Our agreed next step is {newLocation}. I will follow up by {date}. Please let me know privately if I misunderstood anything important.", "Gracias por hablar conmigo sobre {reason}. Aprecio la oportunidad de escuchar. Nuestro próximo paso acordado es {newLocation}. Daré seguimiento antes del {date}. Avíseme en privado si entendí mal algo importante."],
    ["reason", "newLocation", "date"]),
  template("celebrate-effort", "culture", 130, ["Celebrating Effort", "Celebrar el Esfuerzo"],
    ["Recognize repeatable team behaviors.", "Reconoce comportamientos que el equipo puede repetir."],
    ["Great work today, {teamName}! Players kept trying, encouraged teammates, and responded positively to coaching. Please celebrate that effort with them. Those habits matter beyond the final score.", "¡Gran trabajo hoy, {teamName}! Los jugadores siguieron intentando, animaron a sus compañeros y respondieron positivamente al coaching. Celebren ese esfuerzo con ellos. Esos hábitos importan más allá del resultado."],
    ["teamName"]),
  template("sportsmanship", "culture", 140, ["Reinforcing Sportsmanship", "Reforzar la Deportividad"],
    ["Set a positive expectation for everyone.", "Establece una expectativa positiva para todos."],
    ["As we prepare for {date}, please help {teamName} model sportsmanship by encouraging effort, respecting officials, and supporting every player. Adults set the tone from the sideline. Thank you for helping keep the experience positive.", "Mientras nos preparamos para el {date}, ayuden a {teamName} a demostrar deportividad animando el esfuerzo, respetando a los oficiales y apoyando a cada jugador. Los adultos marcan el tono desde la sideline. Gracias por mantener una experiencia positiva."],
    ["date", "teamName"]),
  template("midseason", "culture", 150, ["Midseason Encouragement", "Ánimo de Mitad de Temporada"],
    ["Reconnect families with the team's purpose.", "Vuelve a conectar a las familias con el propósito del equipo."],
    ["We are halfway through the season, and {teamName} has made meaningful progress. Thank you for supporting attendance, effort, and encouragement. Our next focus is {reason}. Let's keep learning and enjoying the season together.", "Estamos a mitad de temporada y {teamName} ha progresado mucho. Gracias por apoyar la asistencia, el esfuerzo y el ánimo. Nuestro próximo enfoque es {reason}. Sigamos aprendiendo y disfrutando juntos."],
    ["teamName", "reason"]),
  template("season-thanks", "culture", 160, ["End-of-Season Thank You", "Agradecimiento de Fin de Temporada"],
    ["Close the season with appreciation.", "Cierra la temporada con agradecimiento."],
    ["Thank you, {teamName} families, for a memorable season. The players showed growth, effort, and care for one another. I appreciate every volunteer and family member who helped. It was a privilege to coach this group.", "Gracias, familias de {teamName}, por una temporada memorable. Los jugadores demostraron crecimiento, esfuerzo y compañerismo. Aprecio a cada voluntario y familiar que ayudó. Fue un privilegio acompañar a este grupo."],
    ["teamName"]),
];
