import type { CoachProTip, CoachProTipCategory } from "@/types/coachResources";

const text = (en: string, es: string) => ({ en, es });
const tip = (id: string, category: CoachProTipCategory, order: number, title: [string, string], body: [string, string], tryThis: [string, string]): CoachProTip => ({
  id, category, sortOrder: order, title: text(...title), body: text(...body), tryThis: text(...tryThis), isActive: true, contentVersion: 1,
});

export const COACH_PRO_TIPS: CoachProTip[] = [
  tip("repeatable-praise", "communication", 10, ["Praise what players can repeat", "Elogia lo que pueden repetir"], ["Instead of only saying “Great job,” name the behavior that worked.", "En vez de decir solo “Buen trabajo”, nombra la conducta que funcionó."], ["Try: “I noticed you looked up before making that pass.”", "Prueba: “Noté que miraste antes de hacer ese pase”."]),
  tip("one-instruction", "instruction", 20, ["Give one instruction at a time", "Da una instrucción a la vez"], ["Young players may stop listening when several directions arrive at once.", "Los jugadores jóvenes pueden dejar de escuchar cuando reciben muchas indicaciones juntas."], ["Tell them what to do, where to go, and when to begin.", "Diles qué hacer, adónde ir y cuándo comenzar."]),
  tip("private-correction", "confidence", 30, ["Correct privately when possible", "Corrige en privado cuando sea posible"], ["Public correction can shift attention from learning to embarrassment.", "Una corrección pública puede cambiar el enfoque del aprendizaje a la vergüenza."], ["Move closer, lower your voice, and give one clear next step.", "Acércate, baja la voz y da un próximo paso claro."]),
  tip("learn-names", "first_time", 40, ["Learn names early", "Aprende los nombres pronto"], ["Using a player’s name helps create belonging and attention.", "Usar el nombre de un jugador ayuda a crear conexión y atención."], ["Greet each player by name as they arrive.", "Saluda a cada jugador por su nombre al llegar."]),
  tip("simple-plan", "first_time", 50, ["Keep the first plan simple", "Mantén sencillo el primer plan"], ["A clear warm-up, two activities, and a positive finish are enough to begin.", "Un calentamiento claro, dos actividades y un cierre positivo son suficientes para empezar."], ["Write your three practice blocks on one small note.", "Escribe los tres bloques de práctica en una nota pequeña."]),
  tip("backup-activity", "practice", 60, ["Always carry a backup activity", "Ten siempre una actividad alternativa"], ["Space, attendance, or equipment can change at the last moment.", "El espacio, la asistencia o el equipo pueden cambiar a último momento."], ["Choose one no-equipment activity that supports today’s skill.", "Elige una actividad sin equipo que apoye la habilidad del día."]),
  tip("short-lines", "practice", 70, ["Shorten the lines", "Reduce las filas"], ["Long lines reduce repetitions and invite distraction.", "Las filas largas reducen repeticiones y facilitan distracciones."], ["Create two small stations instead of one long line.", "Crea dos estaciones pequeñas en vez de una fila larga."]),
  tip("finish-success", "practice", 80, ["Finish with a reachable success", "Termina con un logro alcanzable"], ["Players remember how a practice made them feel.", "Los jugadores recuerdan cómo los hizo sentir una práctica."], ["End with a familiar challenge where everyone can contribute.", "Termina con un reto conocido donde todos puedan contribuir."]),
  tip("notice-recovery", "confidence", 90, ["Notice the recovery", "Reconoce la recuperación"], ["Responding well after a mistake is a skill worth praising.", "Responder bien después de un error es una habilidad que merece elogio."], ["Say: “You reset quickly and got back into the play.”", "Di: “Te recuperaste rápido y volviste a la jugada”."]),
  tip("specific-progress", "confidence", 100, ["Compare players with their own progress", "Compara a cada jugador con su propio progreso"], ["Personal progress builds confidence without creating unnecessary rankings.", "El progreso personal crea confianza sin comparaciones innecesarias."], ["Name one thing the player does more confidently than last week.", "Nombra algo que el jugador hace con más confianza que la semana pasada."]),
  tip("ask-back", "communication", 110, ["Ask players to say it back", "Pide que lo repitan"], ["A quick check reveals whether an instruction was clear.", "Una comprobación rápida muestra si la instrucción fue clara."], ["Ask: “What is our first step when the whistle sounds?”", "Pregunta: “¿Cuál es nuestro primer paso cuando suene el silbato?”"]),
  tip("calm-volume", "communication", 120, ["Use calm volume for important moments", "Usa un volumen tranquilo en momentos importantes"], ["Getting quieter can invite attention more effectively than getting louder.", "Hablar más bajo puede atraer mejor la atención que gritar."], ["Pause, gather the group, then speak in one calm sentence.", "Haz una pausa, reúne al grupo y habla con una frase tranquila."]),
  tip("early-update", "parents", 130, ["Share changes early", "Comparte los cambios temprano"], ["Families can plan better when logistics arrive as soon as they are confirmed.", "Las familias pueden planificar mejor cuando reciben la logística apenas se confirma."], ["Send time, place, what changed, and the next update time.", "Envía hora, lugar, qué cambió y cuándo habrá otra actualización."]),
  tip("private-concern", "parents", 140, ["Move concerns to a private conversation", "Lleva las inquietudes a una conversación privada"], ["Team-wide spaces are not the right place for individual player concerns.", "Los espacios de todo el equipo no son apropiados para inquietudes individuales."], ["Offer two specific times for a calm private conversation.", "Ofrece dos horarios concretos para una conversación privada y tranquila."]),
  tip("listen-first", "parents", 150, ["Listen before explaining", "Escucha antes de explicar"], ["People are more ready for next steps after they feel heard.", "Las personas están más dispuestas a avanzar después de sentirse escuchadas."], ["Begin: “Thank you for telling me. What would you most like me to understand?”", "Comienza: “Gracias por contármelo. ¿Qué es lo más importante que quisiera que entienda?”"]),
  tip("officials", "sportsmanship", 160, ["Model respect for officials", "Modela respeto por los oficiales"], ["Players notice how adults respond to disagreement.", "Los jugadores observan cómo responden los adultos al desacuerdo."], ["Thank the officials after the game, regardless of the result.", "Agradece a los oficiales después del juego, sin importar el resultado."]),
  tip("opponent-effort", "sportsmanship", 170, ["Recognize good play by either team", "Reconoce el buen juego de ambos equipos"], ["Respect for opponents helps competition stay healthy.", "El respeto por el rival ayuda a mantener una competencia sana."], ["Point out one example of teamwork or effort from the other team.", "Señala un ejemplo de trabajo en equipo o esfuerzo del rival."]),
  tip("belonging", "inclusion", 180, ["Design for belonging", "Diseña para que todos pertenezcan"], ["Small adjustments can help more players participate fully.", "Pequeños ajustes pueden ayudar a que más jugadores participen plenamente."], ["Offer a visual demonstration and a spoken instruction.", "Ofrece una demostración visual y una instrucción hablada."]),
  tip("rotate-leaders", "inclusion", 190, ["Rotate leadership moments", "Rota los momentos de liderazgo"], ["The loudest or most skilled player should not always lead.", "El jugador más expresivo o hábil no siempre debe liderar."], ["Invite a different player to demonstrate the warm-up today.", "Invita hoy a un jugador diferente a demostrar el calentamiento."]),
  tip("choice", "inclusion", 200, ["Offer two ways to participate", "Ofrece dos formas de participar"], ["A limited choice can support confidence without changing the goal.", "Una elección limitada puede apoyar la confianza sin cambiar la meta."], ["Let players choose between two starting distances.", "Permite que elijan entre dos distancias iniciales."]),
  tip("one-focus", "game_day", 210, ["Choose one game-day focus", "Elige un enfoque para el juego"], ["Too many goals make it hard for players to know what matters now.", "Demasiadas metas dificultan saber qué importa en el momento."], ["Name one team behavior to notice throughout the game.", "Nombra una conducta del equipo para observar durante el juego."]),
  tip("steady-sideline", "game_day", 220, ["Keep the sideline steady", "Mantén la sideline estable"], ["Players benefit from consistent messages during emotional moments.", "Los jugadores se benefician de mensajes consistentes en momentos emocionales."], ["Use the same short reset phrase after both good and difficult plays.", "Usa la misma frase breve para reiniciar después de jugadas buenas o difíciles."]),
  tip("postgame-question", "game_day", 230, ["Ask one learning question", "Haz una pregunta de aprendizaje"], ["A short reflection can turn the game into the next practice plan.", "Una reflexión breve puede convertir el juego en el próximo plan de práctica."], ["Ask: “What should we practice because of what we noticed today?”", "Pregunta: “¿Qué debemos practicar según lo que notamos hoy?”"]),
  tip("next-action", "mistakes", 240, ["Coach the next action", "Entrena la próxima acción"], ["After a mistake, players need a useful next step more than a replay of the error.", "Después de un error, necesitan un próximo paso útil más que repetir lo ocurrido."], ["Say: “Reset your feet and find the next open space.”", "Di: “Reinicia tus pies y busca el próximo espacio libre”."]),
  tip("normalize-learning", "mistakes", 250, ["Normalize learning mistakes", "Normaliza los errores de aprendizaje"], ["A safe learning environment encourages players to try new skills.", "Un ambiente seguro anima a probar habilidades nuevas."], ["Tell the group one mistake that shows they are attempting today’s skill.", "Dile al grupo qué error demuestra que están intentando la habilidad de hoy."]),
  tip("playful-challenge", "fun", 260, ["Add a playful challenge", "Añade un reto divertido"], ["Fun can increase repetitions without reducing purpose.", "La diversión puede aumentar repeticiones sin perder el propósito."], ["Let the team try to beat its own clean-repetition total.", "Permite que el equipo intente superar su propio total de repeticiones correctas."]),
  tip("player-choice", "fun", 270, ["Let players choose the final activity", "Deja que elijan la actividad final"], ["A small choice can increase ownership and energy.", "Una pequeña elección puede aumentar la participación y energía."], ["Offer two activities that practice the same skill.", "Ofrece dos actividades que practiquen la misma habilidad."]),
  tip("space-scan", "safety", 280, ["Scan the space before players arrive", "Revisa el espacio antes de que lleguen"], ["Early inspection gives you time to address hazards through approved procedures.", "Una inspección temprana da tiempo para atender riesgos mediante procesos aprobados."], ["Walk the boundaries and check surfaces, goals, and shared equipment.", "Recorre los límites y revisa superficies, porterías y equipo compartido."]),
  tip("weather-plan", "safety", 290, ["Know the weather decision process", "Conoce el proceso de decisiones por clima"], ["Coaches should follow league and facility guidance rather than improvise safety rules.", "Los coaches deben seguir las guías de la liga e instalación, no improvisar reglas de seguridad."], ["Save the approved weather contact and procedure before game day.", "Guarda el contacto y procedimiento aprobados antes del juego."]),
  tip("demonstrate", "instruction", 300, ["Show, then let them try", "Muestra y luego deja que prueben"], ["A brief demonstration can be clearer than a long explanation.", "Una demostración breve puede ser más clara que una explicación larga."], ["Demonstrate once, name one cue, and start the activity.", "Demuestra una vez, nombra una clave y comienza la actividad."]),
];
