@echo off
set "APP_VARIANT=production"
set "REQUIRE_PRODUCTION_LEGAL_CONFIG=true"
set "EXPO_PUBLIC_FIREBASE_ENVIRONMENT=production"
set "EXPO_PUBLIC_PRIVACY_POLICY_URL=https://www.joinsidelinesocial.com/privacy"
set "EXPO_PUBLIC_TERMS_OF_USE_URL=https://www.joinsidelinesocial.com/terms"
set "EXPO_PUBLIC_SUPPORT_URL=https://www.joinsidelinesocial.com/support"
set "COACH_AI_REQUIRE_EAS_PRODUCTION=true"
set "COACH_AI_COMPILED_PROFILE=production"
node scripts\test-coach-ai-compiled-environment.cjs
